import { Project } from "@/types/project";

export const PROJECTS : Project[] = [
  {
    title: "Monkey Interpretter",
    subtitle: "An interpreter for a toy programming language called monkey",
    body: "An interpreter for a toy programming language, implemented from the ground up in Go. I started it after I couldn’t get into my university’s compilers course, which is why I decided to learn the subject independently through this project.",
    imageSrc: "/mi-cover.png",
    tech: ["Go"],
    color: "aqua",
    href: "https://github.com/self-sasi/monkey-interpreter",
    horizontal: false,
    reversed: false,
    xl: false,
  },
  {
    title: "simple-ui",
    subtitle: "A UI library that provides easy-to-use components",
    body: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Similique, quam ducimus odio eveniet expedita minus sapiente harum voluptatem repellat modi.",
    imageSrc: "https://images.unsplash.com/photo-1579403124614-197f69d8187b?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8c29mdHdhcmUlMjBkZXZlbG9wbWVudHxlbnwwfHwwfHx8MA%3D%3D",
    tech: ["Next.js", "TypeScript", "Tailwind"],
    color: "azure",
    href: "/projects/playful-landing",
    horizontal: true,
    reversed: true,
    xl: false,
  },
  {
    title: "TaleThread",
    subtitle: "Analytics UI with a clean data story",
    body: "A social media platform that allows users to collaboratively write stories and poems. \n\nUsers can start new threads, contribute to existing ones, rate contributions, and make friends with fellow writers. The platform encourages creativity and community engagement among writers of all levels. \n\nAdditional features include personalized writing prompts, genre-specific communities, and integration with AI tools for inspiration.",
    imageSrc: "/logo.jpeg",
    tech: ["React", "shadcn/ui", "Recharts"],
    color: "indigo-vivid",
    href: "/projects/neon-dashboard",
    horizontal: true,
    reversed: false,
    xl: false,
  },
  {
    title: "Hee Hee Hee Haw",
    subtitle: "ok",
    body: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Similique, quam ducimus odio eveniet expedita minus sapiente harum voluptatem repellat modi.",
    imageSrc:
      "https://cdn.shadcnstudio.com/ss-assets/components/card/image-2.png?height=280&format=auto",
    tech: ["Next.js", "TypeScript", "Tailwind"],
    color: "red",
    href: "/projects/playful-landing",
    horizontal: false,
    reversed: false,
    xl: false,
  },
  {
    title: "Loda Page",
    subtitle: "ma ka loda",
    body: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Similique, quam ducimus odio eveniet expedita minus sapiente harum voluptatem repellat modi.",
    imageSrc: "https://picsum.photos/id/250/200/300",
    tech: ["Next.js", "TypeScript", "Tailwind"],
    color: "grassy",
    href: "/projects/playful-landing",
    horizontal: true,
    reversed: true,
    xl: true,
  }
]